<?php

namespace Database\Seeders;

use App\Models\Municipios;
use Illuminate\Database\Seeder;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $createMultipleMunicipios = [
            ['departamentos_id' => 1, 'nombre' => 'Ahuachapán'],
            ['departamentos_id' => 1, 'nombre' => 'Apaneca'],
            ['departamentos_id' => 1, 'nombre' => 'Atiquizaya'],
            ['departamentos_id' => 1, 'nombre' => 'Concepción de Ataco'],
            ['departamentos_id' => 1, 'nombre' => 'El Refugio'],
            ['departamentos_id' => 1, 'nombre' => 'Guaymango'],
            ['departamentos_id' => 1, 'nombre' => 'Jujutla'],
            ['departamentos_id' => 1, 'nombre' => 'San Francisco Menéndez'],
            ['departamentos_id' => 1, 'nombre' => 'San Lorenzo'],
            ['departamentos_id' => 1, 'nombre' => 'San Pedro Puxtla'],
            ['departamentos_id' => 1, 'nombre' => 'Tacuba'],
            ['departamentos_id' => 1, 'nombre' => 'Turín'],
            ['departamentos_id' => 2, 'nombre' => 'Cinquera'],
            ['departamentos_id' => 2, 'nombre' => 'Dolores'],
            ['departamentos_id' => 2, 'nombre' => 'Guacotecti'],
            ['departamentos_id' => 2, 'nombre' => 'Ilobasco'],
            ['departamentos_id' => 2, 'nombre' => 'Jutiapa'],
            ['departamentos_id' => 2, 'nombre' => 'San Isidro'],
            ['departamentos_id' => 2, 'nombre' => 'Sensuntepeque'],
            ['departamentos_id' => 2, 'nombre' => 'Tejutepeque'],
            ['departamentos_id' => 2, 'nombre' => 'Victoria'],
            ['departamentos_id' => 3, 'nombre' => 'Agua Caliente'],
            ['departamentos_id' => 3, 'nombre' => 'Arcatao'],
            ['departamentos_id' => 3, 'nombre' => 'Azacualpa'],
            ['departamentos_id' => 3, 'nombre' => 'Chalatenango'],
            ['departamentos_id' => 3, 'nombre' => 'Citalá'],
            ['departamentos_id' => 3, 'nombre' => 'Comalapa'],
            ['departamentos_id' => 3, 'nombre' => 'Concepción Quezaltepeque'],
            ['departamentos_id' => 3, 'nombre' => 'Dulce Nombre de María'],
            ['departamentos_id' => 3, 'nombre' => 'El Carrizal'],
            ['departamentos_id' => 3, 'nombre' => 'El Paraíso'],
            ['departamentos_id' => 3, 'nombre' => 'La Laguna'],
            ['departamentos_id' => 3, 'nombre' => 'La Palma'],
            ['departamentos_id' => 3, 'nombre' => 'La Reina'],
            ['departamentos_id' => 3, 'nombre' => 'Las Vueltas'],
            ['departamentos_id' => 3, 'nombre' => 'Nombre de Jesús'],
            ['departamentos_id' => 3, 'nombre' => 'Nueva Concepción'],
            ['departamentos_id' => 3, 'nombre' => 'Nueva Trinidad'],
            ['departamentos_id' => 3, 'nombre' => 'Ojos de Agua'],
            ['departamentos_id' => 3, 'nombre' => 'Potonico'],
            ['departamentos_id' => 3, 'nombre' => 'San Antonio de la Cruz (San Antonio La Cruz)'],
            ['departamentos_id' => 3, 'nombre' => 'San Antonio Los Ranchos (San Antonio Ranchos)'],
            ['departamentos_id' => 3, 'nombre' => 'San Fernando'],
            ['departamentos_id' => 3, 'nombre' => 'San Francisco Lempa'],
            ['departamentos_id' => 3, 'nombre' => 'San Francisco Morazán'],
            ['departamentos_id' => 3, 'nombre' => 'San Ignacio'],
            ['departamentos_id' => 3, 'nombre' => 'San Isidro Labrador'],
            ['departamentos_id' => 3, 'nombre' => 'San José Cancasque'],
            ['departamentos_id' => 3, 'nombre' => 'San José Las Flores'],
            ['departamentos_id' => 3, 'nombre' => 'San Luis del Carmen'],
            ['departamentos_id' => 3, 'nombre' => 'San Miguel de Mercedes'],
            ['departamentos_id' => 3, 'nombre' => 'San Rafael'],
            ['departamentos_id' => 3, 'nombre' => 'Santa Rita'],
            ['departamentos_id' => 3, 'nombre' => 'Tejutla'],
            ['departamentos_id' => 4, 'nombre' => 'Candelaria'],
            ['departamentos_id' => 4, 'nombre' => 'Cojutepeque'],
            ['departamentos_id' => 4, 'nombre' => 'El Carmen'],
            ['departamentos_id' => 4, 'nombre' => 'El Rosario'],
            ['departamentos_id' => 4, 'nombre' => 'Monte San Juan'],
            ['departamentos_id' => 4, 'nombre' => 'Oratorio de Concepción'],
            ['departamentos_id' => 4, 'nombre' => 'San Bartolomé Perulapía'],
            ['departamentos_id' => 4, 'nombre' => 'San Cristóbal'],
            ['departamentos_id' => 4, 'nombre' => 'San José Guayabal'],
            ['departamentos_id' => 4, 'nombre' => 'San Pedro Perulapán'],
            ['departamentos_id' => 4, 'nombre' => 'San Rafael Cedros'],
            ['departamentos_id' => 4, 'nombre' => 'San Ramón'],
            ['departamentos_id' => 4, 'nombre' => 'Santa Cruz Analquito'],
            ['departamentos_id' => 4, 'nombre' => 'Santa Cruz Michapa'],
            ['departamentos_id' => 4, 'nombre' => 'Suchitoto'],
            ['departamentos_id' => 4, 'nombre' => 'Tenancingo'],
            ['departamentos_id' => 4, 'nombre' => 'Zacatecas'],
            ['departamentos_id' => 5, 'nombre' => 'Antiguo Cuscatlán'],
            ['departamentos_id' => 5, 'nombre' => 'Chiltiupán'],
            ['departamentos_id' => 5, 'nombre' => 'Ciudad Arce'],
            ['departamentos_id' => 5, 'nombre' => 'Colón'],
            ['departamentos_id' => 5, 'nombre' => 'Comasagua'],
            ['departamentos_id' => 5, 'nombre' => 'Huizúcar'],
            ['departamentos_id' => 5, 'nombre' => 'Jayaque'],
            ['departamentos_id' => 5, 'nombre' => 'Jicalapa'],
            ['departamentos_id' => 5, 'nombre' => 'La Libertad'],
            ['departamentos_id' => 5, 'nombre' => 'Nuevo Cuscatlán'],
            ['departamentos_id' => 5, 'nombre' => 'Opico'],
            ['departamentos_id' => 5, 'nombre' => 'Quezaltepeque'],
            ['departamentos_id' => 5, 'nombre' => 'Sacacoyo'],
            ['departamentos_id' => 5, 'nombre' => 'San José Villanueva'],
            ['departamentos_id' => 5, 'nombre' => 'San Matías'],
            ['departamentos_id' => 5, 'nombre' => 'San Pablo Tacachico'],
            ['departamentos_id' => 5, 'nombre' => 'Santa Tecla'],
            ['departamentos_id' => 5, 'nombre' => 'Talnique'],
            ['departamentos_id' => 5, 'nombre' => 'Tamanique'],
            ['departamentos_id' => 5, 'nombre' => 'Teotepeque'],
            ['departamentos_id' => 5, 'nombre' => 'Tepecoyo'],
            ['departamentos_id' => 5, 'nombre' => 'Zaragoza'],
            ['departamentos_id' => 6, 'nombre' => 'Cuyultitán'],
            ['departamentos_id' => 6, 'nombre' => 'El Rosario'],
            ['departamentos_id' => 6, 'nombre' => 'Jerusalén'],
            ['departamentos_id' => 6, 'nombre' => 'Mercedes La Ceiba'],
            ['departamentos_id' => 6, 'nombre' => 'Olocuilta'],
            ['departamentos_id' => 6, 'nombre' => 'Paraíso de Osorio'],
            ['departamentos_id' => 6, 'nombre' => 'San Antonio Masahuat'],
            ['departamentos_id' => 6, 'nombre' => 'San Emigdio'],
            ['departamentos_id' => 6, 'nombre' => 'San Francisco Chinameca'],
            ['departamentos_id' => 6, 'nombre' => 'San Juan Nonualco'],
            ['departamentos_id' => 6, 'nombre' => 'San Juan Talpa'],
            ['departamentos_id' => 6, 'nombre' => 'San Juan Tepezontes'],
            ['departamentos_id' => 6, 'nombre' => 'San Luis La Herradura'],
            ['departamentos_id' => 6, 'nombre' => 'San Luis Talpa'],
            ['departamentos_id' => 6, 'nombre' => 'San Miguel Tepezontes'],
            ['departamentos_id' => 6, 'nombre' => 'San Pedro Masahuat'],
            ['departamentos_id' => 6, 'nombre' => 'San Pedro Nonualco'],
            ['departamentos_id' => 6, 'nombre' => 'San Rafael Obrajuelo'],
            ['departamentos_id' => 6, 'nombre' => 'Santa María Ostuma'],
            ['departamentos_id' => 6, 'nombre' => 'Santiago Nonualco'],
            ['departamentos_id' => 6, 'nombre' => 'Tapalhuaca'],
            ['departamentos_id' => 6, 'nombre' => 'Zacatecoluca'],
            ['departamentos_id' => 7, 'nombre' => 'Anamorós'],
            ['departamentos_id' => 7, 'nombre' => 'Bolívar'],
            ['departamentos_id' => 7, 'nombre' => 'Concepción de Oriente'],
            ['departamentos_id' => 7, 'nombre' => 'Conchagua'],
            ['departamentos_id' => 7, 'nombre' => 'El Carmen'],
            ['departamentos_id' => 7, 'nombre' => 'El Sauce'],
            ['departamentos_id' => 7, 'nombre' => 'Intipucá'],
            ['departamentos_id' => 7, 'nombre' => 'La Unión'],
            ['departamentos_id' => 7, 'nombre' => 'Lislique'],
            ['departamentos_id' => 7, 'nombre' => 'Meanguera del Golfo'],
            ['departamentos_id' => 7, 'nombre' => 'Nueva Esparta'],
            ['departamentos_id' => 7, 'nombre' => 'Pasaquina'],
            ['departamentos_id' => 7, 'nombre' => 'Polorós'],
            ['departamentos_id' => 7, 'nombre' => 'San Alejo'],
            ['departamentos_id' => 7, 'nombre' => 'San José'],
            ['departamentos_id' => 7, 'nombre' => 'Santa Rosa de Lima'],
            ['departamentos_id' => 7, 'nombre' => 'Yayantique'],
            ['departamentos_id' => 7, 'nombre' => 'Yucuaiquín'],
            ['departamentos_id' => 8, 'nombre' => 'Arambala'],
            ['departamentos_id' => 8, 'nombre' => 'Cacaopera'],
            ['departamentos_id' => 8, 'nombre' => 'Chilanga'],
            ['departamentos_id' => 8, 'nombre' => 'Corinto'],
            ['departamentos_id' => 8, 'nombre' => 'Delicias de Concepción'],
            ['departamentos_id' => 8, 'nombre' => 'El Divisadero'],
            ['departamentos_id' => 8, 'nombre' => 'El Rosario'],
            ['departamentos_id' => 8, 'nombre' => 'Gualococti'],
            ['departamentos_id' => 8, 'nombre' => 'Guatajiagua'],
            ['departamentos_id' => 8, 'nombre' => 'Joateca'],
            ['departamentos_id' => 8, 'nombre' => 'Jocoaitique'],
            ['departamentos_id' => 8, 'nombre' => 'Jocoro'],
            ['departamentos_id' => 8, 'nombre' => 'Lolotiquillo'],
            ['departamentos_id' => 8, 'nombre' => 'Meanguera'],
            ['departamentos_id' => 8, 'nombre' => 'Osicala'],
            ['departamentos_id' => 8, 'nombre' => 'Perquín'],
            ['departamentos_id' => 8, 'nombre' => 'San Carlos'],
            ['departamentos_id' => 8, 'nombre' => 'San Fernando'],
            ['departamentos_id' => 8, 'nombre' => 'San Francisco Gotera'],
            ['departamentos_id' => 8, 'nombre' => 'San Isidro'],
            ['departamentos_id' => 8, 'nombre' => 'San Simón'],
            ['departamentos_id' => 8, 'nombre' => 'Sensembra'],
            ['departamentos_id' => 8, 'nombre' => 'Sociedad'],
            ['departamentos_id' => 8, 'nombre' => 'Torola'],
            ['departamentos_id' => 8, 'nombre' => 'Yamabal'],
            ['departamentos_id' => 8, 'nombre' => 'Yoloaiquín'],
            ['departamentos_id' => 9, 'nombre' => 'Carolina'],
            ['departamentos_id' => 9, 'nombre' => 'Chapeltique'],
            ['departamentos_id' => 9, 'nombre' => 'Chinameca'],
            ['departamentos_id' => 9, 'nombre' => 'Chirilagua'],
            ['departamentos_id' => 9, 'nombre' => 'Ciudad Barrios'],
            ['departamentos_id' => 9, 'nombre' => 'Comacarán'],
            ['departamentos_id' => 9, 'nombre' => 'El Tránsito'],
            ['departamentos_id' => 9, 'nombre' => 'Lolotique'],
            ['departamentos_id' => 9, 'nombre' => 'Moncagua'],
            ['departamentos_id' => 9, 'nombre' => 'Nueva Guadalupe'],
            ['departamentos_id' => 9, 'nombre' => 'Nuevo Edén de San Juan'],
            ['departamentos_id' => 9, 'nombre' => 'Quelepa'],
            ['departamentos_id' => 9, 'nombre' => 'San Antonio'],
            ['departamentos_id' => 9, 'nombre' => 'San Gerardo'],
            ['departamentos_id' => 9, 'nombre' => 'San Jorge'],
            ['departamentos_id' => 9, 'nombre' => 'San Luis de la Reina'],
            ['departamentos_id' => 9, 'nombre' => 'San Miguel'],
            ['departamentos_id' => 9, 'nombre' => 'San Rafael (San Rafael Oriente)'],
            ['departamentos_id' => 9, 'nombre' => 'Sesori'],
            ['departamentos_id' => 9, 'nombre' => 'Uluazapa'],
            ['departamentos_id' => 10, 'nombre' => 'Aguilares'],
            ['departamentos_id' => 10, 'nombre' => 'Apopa'],
            ['departamentos_id' => 10, 'nombre' => 'Ayutuxtepeque'],
            ['departamentos_id' => 10, 'nombre' => 'Cuscatancingo'],
            ['departamentos_id' => 10, 'nombre' => 'Delgado'],
            ['departamentos_id' => 10, 'nombre' => 'El Paisnal'],
            ['departamentos_id' => 10, 'nombre' => 'Guazapa'],
            ['departamentos_id' => 10, 'nombre' => 'Ilopango'],
            ['departamentos_id' => 10, 'nombre' => 'Mejicanos'],
            ['departamentos_id' => 10, 'nombre' => 'Nejapa'],
            ['departamentos_id' => 10, 'nombre' => 'Panchimalco'],
            ['departamentos_id' => 10, 'nombre' => 'Rosario de Mora'],
            ['departamentos_id' => 10, 'nombre' => 'San Marcos'],
            ['departamentos_id' => 10, 'nombre' => 'San Martín'],
            ['departamentos_id' => 10, 'nombre' => 'San Salvador'],
            ['departamentos_id' => 10, 'nombre' => 'Santiago Texacuangos'],
            ['departamentos_id' => 10, 'nombre' => 'Santo Tomás'],
            ['departamentos_id' => 10, 'nombre' => 'Soyapango'],
            ['departamentos_id' => 10, 'nombre' => 'Tonacatepeque'],
            ['departamentos_id' => 11, 'nombre' => 'Apastepeque'],
            ['departamentos_id' => 11, 'nombre' => 'Guadalupe'],
            ['departamentos_id' => 11, 'nombre' => 'San Cayetano Istepeque'],
            ['departamentos_id' => 11, 'nombre' => 'San Esteban Catarina'],
            ['departamentos_id' => 11, 'nombre' => 'San Ildefonso'],
            ['departamentos_id' => 11, 'nombre' => 'San Lorenzo'],
            ['departamentos_id' => 11, 'nombre' => 'San Sebastián'],
            ['departamentos_id' => 11, 'nombre' => 'San Vicente'],
            ['departamentos_id' => 11, 'nombre' => 'Santa Clara'],
            ['departamentos_id' => 11, 'nombre' => 'Santo Domingo'],
            ['departamentos_id' => 11, 'nombre' => 'Tecoluca'],
            ['departamentos_id' => 11, 'nombre' => 'Tepetitán'],
            ['departamentos_id' => 11, 'nombre' => 'Verapaz'],
            ['departamentos_id' => 12, 'nombre' => 'Candelaria de la Frontera'],
            ['departamentos_id' => 12, 'nombre' => 'Chalchuapa'],
            ['departamentos_id' => 12, 'nombre' => 'Coatepeque'],
            ['departamentos_id' => 12, 'nombre' => 'El Congo'],
            ['departamentos_id' => 12, 'nombre' => 'El Porvenir'],
            ['departamentos_id' => 12, 'nombre' => 'Masahuat'],
            ['departamentos_id' => 12, 'nombre' => 'Metapán'],
            ['departamentos_id' => 12, 'nombre' => 'San Antonio Pajonal'],
            ['departamentos_id' => 12, 'nombre' => 'San Sebastián Salitrillo'],
            ['departamentos_id' => 12, 'nombre' => 'Santa Ana'],
            ['departamentos_id' => 12, 'nombre' => 'Santa Rosa Guachipilín'],
            ['departamentos_id' => 12, 'nombre' => 'Santiago de la Frontera'],
            ['departamentos_id' => 12, 'nombre' => 'Texistepeque'],
            ['departamentos_id' => 13, 'nombre' => 'Acajutla'],
            ['departamentos_id' => 13, 'nombre' => 'Armenia'],
            ['departamentos_id' => 13, 'nombre' => 'Caluco'],
            ['departamentos_id' => 13, 'nombre' => 'Cuisnahuat'],
            ['departamentos_id' => 13, 'nombre' => 'Izalco'],
            ['departamentos_id' => 13, 'nombre' => 'Juayúa'],
            ['departamentos_id' => 13, 'nombre' => 'Nahuizalco'],
            ['departamentos_id' => 13, 'nombre' => 'Nahulingo'],
            ['departamentos_id' => 13, 'nombre' => 'Salcoatitán'],
            ['departamentos_id' => 13, 'nombre' => 'San Antonio del Monte'],
            ['departamentos_id' => 13, 'nombre' => 'San Julián'],
            ['departamentos_id' => 13, 'nombre' => 'Santa Catarina Masahuat'],
            ['departamentos_id' => 13, 'nombre' => 'Santa Isabel Ishuatán'],
            ['departamentos_id' => 13, 'nombre' => 'Santo Domingo'],
            ['departamentos_id' => 13, 'nombre' => 'Sonsonate'],
            ['departamentos_id' => 13, 'nombre' => 'Sonzacate'],
            ['departamentos_id' => 14, 'nombre' => 'Alegría'],
            ['departamentos_id' => 14, 'nombre' => 'Berlín'],
            ['departamentos_id' => 14, 'nombre' => 'California'],
            ['departamentos_id' => 14, 'nombre' => 'Concepción Batres'],
            ['departamentos_id' => 14, 'nombre' => 'El Triunfo'],
            ['departamentos_id' => 14, 'nombre' => 'Ereguayquín'],
            ['departamentos_id' => 14, 'nombre' => 'Estanzuelas'],
            ['departamentos_id' => 14, 'nombre' => 'Jiquilisco'],
            ['departamentos_id' => 14, 'nombre' => 'Jucuapa'],
            ['departamentos_id' => 14, 'nombre' => 'Jucuarán'],
            ['departamentos_id' => 14, 'nombre' => 'Mercedes Umaña'],
            ['departamentos_id' => 14, 'nombre' => 'Nueva Granada'],
            ['departamentos_id' => 14, 'nombre' => 'Ozatlán'],
            ['departamentos_id' => 14, 'nombre' => 'Puerto El Triunfo'],
            ['departamentos_id' => 14, 'nombre' => 'San Agustín'],
            ['departamentos_id' => 14, 'nombre' => 'San Buenaventura'],
            ['departamentos_id' => 14, 'nombre' => 'San Dionisio'],
            ['departamentos_id' => 14, 'nombre' => 'San Francisco Javier'],
            ['departamentos_id' => 14, 'nombre' => 'Santa Elena'],
            ['departamentos_id' => 14, 'nombre' => 'Santa María'],
            ['departamentos_id' => 14, 'nombre' => 'Santiago de María'],
            ['departamentos_id' => 14, 'nombre' => 'Tecapán'],
            ['departamentos_id' => 14, 'nombre' => 'Usulután'],
        ];

        Municipios::insert($createMultipleMunicipios);
    }
}